//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("veterinariaDBModel", "FK__Animales__Cedula__0519C6AF", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Datos.Cliente), "Animales", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.Animale), true)]
[assembly: EdmRelationshipAttribute("veterinariaDBModel", "FK__Vacunas__ID_Anim__09DE7BCC", "Animales", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Datos.Animale), "Vacunas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.Vacuna), true)]
[assembly: EdmRelationshipAttribute("veterinariaDBModel", "FK__Vermifugo__ID_An__0EA330E9", "Animales", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Datos.Animale), "Vermifugos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.Vermifugo), true)]
[assembly: EdmRelationshipAttribute("veterinariaDBModel", "FK__Venta_Fac__Cedul__1FCDBCEB", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Datos.Cliente), "Venta_Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.Venta_Factura), true)]
[assembly: EdmRelationshipAttribute("veterinariaDBModel", "FK__Venta_Det__ID_Pr__267ABA7A", "Conceptos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Datos.Concepto), "Venta_Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.Venta_Detalle), true)]
[assembly: EdmRelationshipAttribute("veterinariaDBModel", "FK__Usuarios__ID_Rol__173876EA", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Datos.Role), "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.Usuario), true)]
[assembly: EdmRelationshipAttribute("veterinariaDBModel", "FK__Venta_Fac__ID_Us__20C1E124", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Datos.Usuario), "Venta_Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.Venta_Factura), true)]
[assembly: EdmRelationshipAttribute("veterinariaDBModel", "FK__Venta_Det__ID_Fa__25869641", "Venta_Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Datos.Venta_Factura), "Venta_Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Datos.Venta_Detalle), true)]

#endregion

namespace Datos
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class veterinariaDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new veterinariaDBEntities object using the connection string found in the 'veterinariaDBEntities' section of the application configuration file.
        /// </summary>
        public veterinariaDBEntities() : base("name=veterinariaDBEntities", "veterinariaDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new veterinariaDBEntities object.
        /// </summary>
        public veterinariaDBEntities(string connectionString) : base(connectionString, "veterinariaDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new veterinariaDBEntities object.
        /// </summary>
        public veterinariaDBEntities(EntityConnection connection) : base(connection, "veterinariaDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Animale> Animales
        {
            get
            {
                if ((_Animales == null))
                {
                    _Animales = base.CreateObjectSet<Animale>("Animales");
                }
                return _Animales;
            }
        }
        private ObjectSet<Animale> _Animales;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Concepto> Conceptos
        {
            get
            {
                if ((_Conceptos == null))
                {
                    _Conceptos = base.CreateObjectSet<Concepto>("Conceptos");
                }
                return _Conceptos;
            }
        }
        private ObjectSet<Concepto> _Conceptos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vacuna> Vacunas
        {
            get
            {
                if ((_Vacunas == null))
                {
                    _Vacunas = base.CreateObjectSet<Vacuna>("Vacunas");
                }
                return _Vacunas;
            }
        }
        private ObjectSet<Vacuna> _Vacunas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Venta_Detalle> Venta_Detalle
        {
            get
            {
                if ((_Venta_Detalle == null))
                {
                    _Venta_Detalle = base.CreateObjectSet<Venta_Detalle>("Venta_Detalle");
                }
                return _Venta_Detalle;
            }
        }
        private ObjectSet<Venta_Detalle> _Venta_Detalle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Venta_Factura> Venta_Factura
        {
            get
            {
                if ((_Venta_Factura == null))
                {
                    _Venta_Factura = base.CreateObjectSet<Venta_Factura>("Venta_Factura");
                }
                return _Venta_Factura;
            }
        }
        private ObjectSet<Venta_Factura> _Venta_Factura;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vermifugo> Vermifugos
        {
            get
            {
                if ((_Vermifugos == null))
                {
                    _Vermifugos = base.CreateObjectSet<Vermifugo>("Vermifugos");
                }
                return _Vermifugos;
            }
        }
        private ObjectSet<Vermifugo> _Vermifugos;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Animales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnimales(Animale animale)
        {
            base.AddObject("Animales", animale);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Conceptos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConceptos(Concepto concepto)
        {
            base.AddObject("Conceptos", concepto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vacunas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVacunas(Vacuna vacuna)
        {
            base.AddObject("Vacunas", vacuna);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Venta_Detalle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVenta_Detalle(Venta_Detalle venta_Detalle)
        {
            base.AddObject("Venta_Detalle", venta_Detalle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Venta_Factura EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVenta_Factura(Venta_Factura venta_Factura)
        {
            base.AddObject("Venta_Factura", venta_Factura);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vermifugos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVermifugos(Vermifugo vermifugo)
        {
            base.AddObject("Vermifugos", vermifugo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Animale")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Animale : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Animale object.
        /// </summary>
        /// <param name="iD_Animal">Initial value of the ID_Animal property.</param>
        public static Animale CreateAnimale(global::System.Int32 iD_Animal)
        {
            Animale animale = new Animale();
            animale.ID_Animal = iD_Animal;
            return animale;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Animal
        {
            get
            {
                return _ID_Animal;
            }
            set
            {
                if (_ID_Animal != value)
                {
                    OnID_AnimalChanging(value);
                    ReportPropertyChanging("ID_Animal");
                    _ID_Animal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Animal");
                    OnID_AnimalChanged();
                }
            }
        }
        private global::System.Int32 _ID_Animal;
        partial void OnID_AnimalChanging(global::System.Int32 value);
        partial void OnID_AnimalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                OnCedulaChanging(value);
                ReportPropertyChanging("Cedula");
                _Cedula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cedula");
                OnCedulaChanged();
            }
        }
        private global::System.String _Cedula;
        partial void OnCedulaChanging(global::System.String value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Raza
        {
            get
            {
                return _Raza;
            }
            set
            {
                OnRazaChanging(value);
                ReportPropertyChanging("Raza");
                _Raza = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Raza");
                OnRazaChanged();
            }
        }
        private global::System.String _Raza;
        partial void OnRazaChanging(global::System.String value);
        partial void OnRazaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Especie
        {
            get
            {
                return _Especie;
            }
            set
            {
                OnEspecieChanging(value);
                ReportPropertyChanging("Especie");
                _Especie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Especie");
                OnEspecieChanged();
            }
        }
        private global::System.String _Especie;
        partial void OnEspecieChanging(global::System.String value);
        partial void OnEspecieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.String _Sexo;
        partial void OnSexoChanging(global::System.String value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_Nac
        {
            get
            {
                return _Fecha_Nac;
            }
            set
            {
                OnFecha_NacChanging(value);
                ReportPropertyChanging("Fecha_Nac");
                _Fecha_Nac = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Nac");
                OnFecha_NacChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_Nac;
        partial void OnFecha_NacChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_NacChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Animales__Cedula__0519C6AF", "Clientes")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("veterinariaDBModel.FK__Animales__Cedula__0519C6AF", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("veterinariaDBModel.FK__Animales__Cedula__0519C6AF", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("veterinariaDBModel.FK__Animales__Cedula__0519C6AF", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("veterinariaDBModel.FK__Animales__Cedula__0519C6AF", "Clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Vacunas__ID_Anim__09DE7BCC", "Vacunas")]
        public EntityCollection<Vacuna> Vacunas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vacuna>("veterinariaDBModel.FK__Vacunas__ID_Anim__09DE7BCC", "Vacunas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vacuna>("veterinariaDBModel.FK__Vacunas__ID_Anim__09DE7BCC", "Vacunas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Vermifugo__ID_An__0EA330E9", "Vermifugos")]
        public EntityCollection<Vermifugo> Vermifugos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vermifugo>("veterinariaDBModel.FK__Vermifugo__ID_An__0EA330E9", "Vermifugos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vermifugo>("veterinariaDBModel.FK__Vermifugo__ID_An__0EA330E9", "Vermifugos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="cedula">Initial value of the Cedula property.</param>
        public static Cliente CreateCliente(global::System.String cedula)
        {
            Cliente cliente = new Cliente();
            cliente.Cedula = cedula;
            return cliente;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                if (_Cedula != value)
                {
                    OnCedulaChanging(value);
                    ReportPropertyChanging("Cedula");
                    _Cedula = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Cedula");
                    OnCedulaChanged();
                }
            }
        }
        private global::System.String _Cedula;
        partial void OnCedulaChanging(global::System.String value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_Creacion
        {
            get
            {
                return _Fecha_Creacion;
            }
            set
            {
                OnFecha_CreacionChanging(value);
                ReportPropertyChanging("Fecha_Creacion");
                _Fecha_Creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Creacion");
                OnFecha_CreacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_Creacion;
        partial void OnFecha_CreacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_CreacionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Animales__Cedula__0519C6AF", "Animales")]
        public EntityCollection<Animale> Animales
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Animale>("veterinariaDBModel.FK__Animales__Cedula__0519C6AF", "Animales");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Animale>("veterinariaDBModel.FK__Animales__Cedula__0519C6AF", "Animales", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Venta_Fac__Cedul__1FCDBCEB", "Venta_Factura")]
        public EntityCollection<Venta_Factura> Venta_Factura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta_Factura>("veterinariaDBModel.FK__Venta_Fac__Cedul__1FCDBCEB", "Venta_Factura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta_Factura>("veterinariaDBModel.FK__Venta_Fac__Cedul__1FCDBCEB", "Venta_Factura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Concepto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Concepto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Concepto object.
        /// </summary>
        /// <param name="iD_Producto">Initial value of the ID_Producto property.</param>
        public static Concepto CreateConcepto(global::System.Int32 iD_Producto)
        {
            Concepto concepto = new Concepto();
            concepto.ID_Producto = iD_Producto;
            return concepto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                if (_ID_Producto != value)
                {
                    OnID_ProductoChanging(value);
                    ReportPropertyChanging("ID_Producto");
                    _ID_Producto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Producto");
                    OnID_ProductoChanged();
                }
            }
        }
        private global::System.Int32 _ID_Producto;
        partial void OnID_ProductoChanging(global::System.Int32 value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Producto
        {
            get
            {
                return _Producto;
            }
            set
            {
                OnProductoChanging(value);
                ReportPropertyChanging("Producto");
                _Producto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Producto");
                OnProductoChanged();
            }
        }
        private global::System.String _Producto;
        partial void OnProductoChanging(global::System.String value);
        partial void OnProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio;
        partial void OnPrecioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad_Existente
        {
            get
            {
                return _Cantidad_Existente;
            }
            set
            {
                OnCantidad_ExistenteChanging(value);
                ReportPropertyChanging("Cantidad_Existente");
                _Cantidad_Existente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad_Existente");
                OnCantidad_ExistenteChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad_Existente;
        partial void OnCantidad_ExistenteChanging(Nullable<global::System.Int32> value);
        partial void OnCantidad_ExistenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.String _Estatus;
        partial void OnEstatusChanging(global::System.String value);
        partial void OnEstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Venta_Det__ID_Pr__267ABA7A", "Venta_Detalle")]
        public EntityCollection<Venta_Detalle> Venta_Detalle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta_Detalle>("veterinariaDBModel.FK__Venta_Det__ID_Pr__267ABA7A", "Venta_Detalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta_Detalle>("veterinariaDBModel.FK__Venta_Det__ID_Pr__267ABA7A", "Venta_Detalle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="iD_Rol">Initial value of the ID_Rol property.</param>
        public static Role CreateRole(global::System.Int32 iD_Rol)
        {
            Role role = new Role();
            role.ID_Rol = iD_Rol;
            return role;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Rol
        {
            get
            {
                return _ID_Rol;
            }
            set
            {
                if (_ID_Rol != value)
                {
                    OnID_RolChanging(value);
                    ReportPropertyChanging("ID_Rol");
                    _ID_Rol = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Rol");
                    OnID_RolChanged();
                }
            }
        }
        private global::System.Int32 _ID_Rol;
        partial void OnID_RolChanging(global::System.Int32 value);
        partial void OnID_RolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rol
        {
            get
            {
                return _Rol;
            }
            set
            {
                OnRolChanging(value);
                ReportPropertyChanging("Rol");
                _Rol = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rol");
                OnRolChanged();
            }
        }
        private global::System.String _Rol;
        partial void OnRolChanging(global::System.String value);
        partial void OnRolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Permisos
        {
            get
            {
                return _Permisos;
            }
            set
            {
                OnPermisosChanging(value);
                ReportPropertyChanging("Permisos");
                _Permisos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Permisos");
                OnPermisosChanged();
            }
        }
        private Nullable<global::System.Int32> _Permisos;
        partial void OnPermisosChanging(Nullable<global::System.Int32> value);
        partial void OnPermisosChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Usuarios__ID_Rol__173876EA", "Usuarios")]
        public EntityCollection<Usuario> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("veterinariaDBModel.FK__Usuarios__ID_Rol__173876EA", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("veterinariaDBModel.FK__Usuarios__ID_Rol__173876EA", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="iD_Usuario">Initial value of the ID_Usuario property.</param>
        public static Usuario CreateUsuario(global::System.Int32 iD_Usuario)
        {
            Usuario usuario = new Usuario();
            usuario.ID_Usuario = iD_Usuario;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                if (_ID_Usuario != value)
                {
                    OnID_UsuarioChanging(value);
                    ReportPropertyChanging("ID_Usuario");
                    _ID_Usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Usuario");
                    OnID_UsuarioChanged();
                }
            }
        }
        private global::System.Int32 _ID_Usuario;
        partial void OnID_UsuarioChanging(global::System.Int32 value);
        partial void OnID_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Rol
        {
            get
            {
                return _ID_Rol;
            }
            set
            {
                OnID_RolChanging(value);
                ReportPropertyChanging("ID_Rol");
                _ID_Rol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Rol");
                OnID_RolChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Rol;
        partial void OnID_RolChanging(Nullable<global::System.Int32> value);
        partial void OnID_RolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Usuario
        {
            get
            {
                return _Nombre_Usuario;
            }
            set
            {
                OnNombre_UsuarioChanging(value);
                ReportPropertyChanging("Nombre_Usuario");
                _Nombre_Usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre_Usuario");
                OnNombre_UsuarioChanged();
            }
        }
        private global::System.String _Nombre_Usuario;
        partial void OnNombre_UsuarioChanging(global::System.String value);
        partial void OnNombre_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contrasena
        {
            get
            {
                return _Contrasena;
            }
            set
            {
                OnContrasenaChanging(value);
                ReportPropertyChanging("Contrasena");
                _Contrasena = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contrasena");
                OnContrasenaChanged();
            }
        }
        private global::System.String _Contrasena;
        partial void OnContrasenaChanging(global::System.String value);
        partial void OnContrasenaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Usuarios__ID_Rol__173876EA", "Roles")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("veterinariaDBModel.FK__Usuarios__ID_Rol__173876EA", "Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("veterinariaDBModel.FK__Usuarios__ID_Rol__173876EA", "Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("veterinariaDBModel.FK__Usuarios__ID_Rol__173876EA", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("veterinariaDBModel.FK__Usuarios__ID_Rol__173876EA", "Roles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Venta_Fac__ID_Us__20C1E124", "Venta_Factura")]
        public EntityCollection<Venta_Factura> Venta_Factura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta_Factura>("veterinariaDBModel.FK__Venta_Fac__ID_Us__20C1E124", "Venta_Factura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta_Factura>("veterinariaDBModel.FK__Venta_Fac__ID_Us__20C1E124", "Venta_Factura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Vacuna")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vacuna : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vacuna object.
        /// </summary>
        /// <param name="iD_Vacuna">Initial value of the ID_Vacuna property.</param>
        /// <param name="iD_Animal">Initial value of the ID_Animal property.</param>
        /// <param name="fecha_Vacuna">Initial value of the Fecha_Vacuna property.</param>
        public static Vacuna CreateVacuna(global::System.Int32 iD_Vacuna, global::System.Int32 iD_Animal, global::System.DateTime fecha_Vacuna)
        {
            Vacuna vacuna = new Vacuna();
            vacuna.ID_Vacuna = iD_Vacuna;
            vacuna.ID_Animal = iD_Animal;
            vacuna.Fecha_Vacuna = fecha_Vacuna;
            return vacuna;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Vacuna
        {
            get
            {
                return _ID_Vacuna;
            }
            set
            {
                if (_ID_Vacuna != value)
                {
                    OnID_VacunaChanging(value);
                    ReportPropertyChanging("ID_Vacuna");
                    _ID_Vacuna = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Vacuna");
                    OnID_VacunaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Vacuna;
        partial void OnID_VacunaChanging(global::System.Int32 value);
        partial void OnID_VacunaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Animal
        {
            get
            {
                return _ID_Animal;
            }
            set
            {
                OnID_AnimalChanging(value);
                ReportPropertyChanging("ID_Animal");
                _ID_Animal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Animal");
                OnID_AnimalChanged();
            }
        }
        private global::System.Int32 _ID_Animal;
        partial void OnID_AnimalChanging(global::System.Int32 value);
        partial void OnID_AnimalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Vacuna
        {
            get
            {
                return _Nombre_Vacuna;
            }
            set
            {
                OnNombre_VacunaChanging(value);
                ReportPropertyChanging("Nombre_Vacuna");
                _Nombre_Vacuna = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre_Vacuna");
                OnNombre_VacunaChanged();
            }
        }
        private global::System.String _Nombre_Vacuna;
        partial void OnNombre_VacunaChanging(global::System.String value);
        partial void OnNombre_VacunaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Veterinario
        {
            get
            {
                return _Veterinario;
            }
            set
            {
                OnVeterinarioChanging(value);
                ReportPropertyChanging("Veterinario");
                _Veterinario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Veterinario");
                OnVeterinarioChanged();
            }
        }
        private global::System.String _Veterinario;
        partial void OnVeterinarioChanging(global::System.String value);
        partial void OnVeterinarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha_Vacuna
        {
            get
            {
                return _Fecha_Vacuna;
            }
            set
            {
                OnFecha_VacunaChanging(value);
                ReportPropertyChanging("Fecha_Vacuna");
                _Fecha_Vacuna = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Vacuna");
                OnFecha_VacunaChanged();
            }
        }
        private global::System.DateTime _Fecha_Vacuna;
        partial void OnFecha_VacunaChanging(global::System.DateTime value);
        partial void OnFecha_VacunaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Vacunas__ID_Anim__09DE7BCC", "Animales")]
        public Animale Animale
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Animale>("veterinariaDBModel.FK__Vacunas__ID_Anim__09DE7BCC", "Animales").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Animale>("veterinariaDBModel.FK__Vacunas__ID_Anim__09DE7BCC", "Animales").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Animale> AnimaleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Animale>("veterinariaDBModel.FK__Vacunas__ID_Anim__09DE7BCC", "Animales");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Animale>("veterinariaDBModel.FK__Vacunas__ID_Anim__09DE7BCC", "Animales", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Venta_Detalle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta_Detalle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Venta_Detalle object.
        /// </summary>
        /// <param name="iD_Detalle">Initial value of the ID_Detalle property.</param>
        public static Venta_Detalle CreateVenta_Detalle(global::System.Int32 iD_Detalle)
        {
            Venta_Detalle venta_Detalle = new Venta_Detalle();
            venta_Detalle.ID_Detalle = iD_Detalle;
            return venta_Detalle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Detalle
        {
            get
            {
                return _ID_Detalle;
            }
            set
            {
                if (_ID_Detalle != value)
                {
                    OnID_DetalleChanging(value);
                    ReportPropertyChanging("ID_Detalle");
                    _ID_Detalle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Detalle");
                    OnID_DetalleChanged();
                }
            }
        }
        private global::System.Int32 _ID_Detalle;
        partial void OnID_DetalleChanging(global::System.Int32 value);
        partial void OnID_DetalleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Factura
        {
            get
            {
                return _ID_Factura;
            }
            set
            {
                OnID_FacturaChanging(value);
                ReportPropertyChanging("ID_Factura");
                _ID_Factura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Factura");
                OnID_FacturaChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Factura;
        partial void OnID_FacturaChanging(Nullable<global::System.Int32> value);
        partial void OnID_FacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                OnID_ProductoChanging(value);
                ReportPropertyChanging("ID_Producto");
                _ID_Producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Producto");
                OnID_ProductoChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Producto;
        partial void OnID_ProductoChanging(Nullable<global::System.Int32> value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio;
        partial void OnPrecioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad;
        partial void OnCantidadChanging(Nullable<global::System.Int32> value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Descuento
        {
            get
            {
                return _Descuento;
            }
            set
            {
                OnDescuentoChanging(value);
                ReportPropertyChanging("Descuento");
                _Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Descuento");
                OnDescuentoChanged();
            }
        }
        private Nullable<global::System.Int32> _Descuento;
        partial void OnDescuentoChanging(Nullable<global::System.Int32> value);
        partial void OnDescuentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total;
        partial void OnTotalChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Venta_Det__ID_Pr__267ABA7A", "Conceptos")]
        public Concepto Concepto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concepto>("veterinariaDBModel.FK__Venta_Det__ID_Pr__267ABA7A", "Conceptos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concepto>("veterinariaDBModel.FK__Venta_Det__ID_Pr__267ABA7A", "Conceptos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Concepto> ConceptoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concepto>("veterinariaDBModel.FK__Venta_Det__ID_Pr__267ABA7A", "Conceptos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Concepto>("veterinariaDBModel.FK__Venta_Det__ID_Pr__267ABA7A", "Conceptos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Venta_Det__ID_Fa__25869641", "Venta_Factura")]
        public Venta_Factura Venta_Factura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta_Factura>("veterinariaDBModel.FK__Venta_Det__ID_Fa__25869641", "Venta_Factura").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta_Factura>("veterinariaDBModel.FK__Venta_Det__ID_Fa__25869641", "Venta_Factura").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Venta_Factura> Venta_FacturaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta_Factura>("veterinariaDBModel.FK__Venta_Det__ID_Fa__25869641", "Venta_Factura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Venta_Factura>("veterinariaDBModel.FK__Venta_Det__ID_Fa__25869641", "Venta_Factura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Venta_Factura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta_Factura : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Venta_Factura object.
        /// </summary>
        /// <param name="iD_Factura">Initial value of the ID_Factura property.</param>
        public static Venta_Factura CreateVenta_Factura(global::System.Int32 iD_Factura)
        {
            Venta_Factura venta_Factura = new Venta_Factura();
            venta_Factura.ID_Factura = iD_Factura;
            return venta_Factura;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Factura
        {
            get
            {
                return _ID_Factura;
            }
            set
            {
                if (_ID_Factura != value)
                {
                    OnID_FacturaChanging(value);
                    ReportPropertyChanging("ID_Factura");
                    _ID_Factura = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Factura");
                    OnID_FacturaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Factura;
        partial void OnID_FacturaChanging(global::System.Int32 value);
        partial void OnID_FacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                OnCedulaChanging(value);
                ReportPropertyChanging("Cedula");
                _Cedula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cedula");
                OnCedulaChanged();
            }
        }
        private global::System.String _Cedula;
        partial void OnCedulaChanging(global::System.String value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                OnID_UsuarioChanging(value);
                ReportPropertyChanging("ID_Usuario");
                _ID_Usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Usuario");
                OnID_UsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Usuario;
        partial void OnID_UsuarioChanging(Nullable<global::System.Int32> value);
        partial void OnID_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacion
        {
            get
            {
                return _Observacion;
            }
            set
            {
                OnObservacionChanging(value);
                ReportPropertyChanging("Observacion");
                _Observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacion");
                OnObservacionChanged();
            }
        }
        private global::System.String _Observacion;
        partial void OnObservacionChanging(global::System.String value);
        partial void OnObservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_Venta
        {
            get
            {
                return _Fecha_Venta;
            }
            set
            {
                OnFecha_VentaChanging(value);
                ReportPropertyChanging("Fecha_Venta");
                _Fecha_Venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Venta");
                OnFecha_VentaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_Venta;
        partial void OnFecha_VentaChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_VentaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Venta_Fac__Cedul__1FCDBCEB", "Clientes")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("veterinariaDBModel.FK__Venta_Fac__Cedul__1FCDBCEB", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("veterinariaDBModel.FK__Venta_Fac__Cedul__1FCDBCEB", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("veterinariaDBModel.FK__Venta_Fac__Cedul__1FCDBCEB", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("veterinariaDBModel.FK__Venta_Fac__Cedul__1FCDBCEB", "Clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Venta_Fac__ID_Us__20C1E124", "Usuarios")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("veterinariaDBModel.FK__Venta_Fac__ID_Us__20C1E124", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("veterinariaDBModel.FK__Venta_Fac__ID_Us__20C1E124", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("veterinariaDBModel.FK__Venta_Fac__ID_Us__20C1E124", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("veterinariaDBModel.FK__Venta_Fac__ID_Us__20C1E124", "Usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Venta_Det__ID_Fa__25869641", "Venta_Detalle")]
        public EntityCollection<Venta_Detalle> Venta_Detalle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta_Detalle>("veterinariaDBModel.FK__Venta_Det__ID_Fa__25869641", "Venta_Detalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta_Detalle>("veterinariaDBModel.FK__Venta_Det__ID_Fa__25869641", "Venta_Detalle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veterinariaDBModel", Name="Vermifugo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vermifugo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vermifugo object.
        /// </summary>
        /// <param name="iD_Vermifugos">Initial value of the ID_Vermifugos property.</param>
        /// <param name="iD_Animal">Initial value of the ID_Animal property.</param>
        /// <param name="vermifugo1">Initial value of the Vermifugo1 property.</param>
        /// <param name="resultados">Initial value of the Resultados property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        public static Vermifugo CreateVermifugo(global::System.Int32 iD_Vermifugos, global::System.Int32 iD_Animal, global::System.String vermifugo1, global::System.String resultados, global::System.DateTime fecha)
        {
            Vermifugo vermifugo = new Vermifugo();
            vermifugo.ID_Vermifugos = iD_Vermifugos;
            vermifugo.ID_Animal = iD_Animal;
            vermifugo.Vermifugo1 = vermifugo1;
            vermifugo.Resultados = resultados;
            vermifugo.Fecha = fecha;
            return vermifugo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Vermifugos
        {
            get
            {
                return _ID_Vermifugos;
            }
            set
            {
                if (_ID_Vermifugos != value)
                {
                    OnID_VermifugosChanging(value);
                    ReportPropertyChanging("ID_Vermifugos");
                    _ID_Vermifugos = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Vermifugos");
                    OnID_VermifugosChanged();
                }
            }
        }
        private global::System.Int32 _ID_Vermifugos;
        partial void OnID_VermifugosChanging(global::System.Int32 value);
        partial void OnID_VermifugosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Animal
        {
            get
            {
                return _ID_Animal;
            }
            set
            {
                OnID_AnimalChanging(value);
                ReportPropertyChanging("ID_Animal");
                _ID_Animal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Animal");
                OnID_AnimalChanged();
            }
        }
        private global::System.Int32 _ID_Animal;
        partial void OnID_AnimalChanging(global::System.Int32 value);
        partial void OnID_AnimalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Vermifugo1
        {
            get
            {
                return _Vermifugo1;
            }
            set
            {
                OnVermifugo1Changing(value);
                ReportPropertyChanging("Vermifugo1");
                _Vermifugo1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Vermifugo1");
                OnVermifugo1Changed();
            }
        }
        private global::System.String _Vermifugo1;
        partial void OnVermifugo1Changing(global::System.String value);
        partial void OnVermifugo1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Resultados
        {
            get
            {
                return _Resultados;
            }
            set
            {
                OnResultadosChanging(value);
                ReportPropertyChanging("Resultados");
                _Resultados = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Resultados");
                OnResultadosChanged();
            }
        }
        private global::System.String _Resultados;
        partial void OnResultadosChanging(global::System.String value);
        partial void OnResultadosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veterinariaDBModel", "FK__Vermifugo__ID_An__0EA330E9", "Animales")]
        public Animale Animale
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Animale>("veterinariaDBModel.FK__Vermifugo__ID_An__0EA330E9", "Animales").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Animale>("veterinariaDBModel.FK__Vermifugo__ID_An__0EA330E9", "Animales").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Animale> AnimaleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Animale>("veterinariaDBModel.FK__Vermifugo__ID_An__0EA330E9", "Animales");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Animale>("veterinariaDBModel.FK__Vermifugo__ID_An__0EA330E9", "Animales", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
